### ISSUE TITLE
Peer to peer code review feedback.

### ISSUE THREAD

**Issue by Omar-Muhamad** [Omar-Muhamad/Portfolio-Full-Vesion#8]

**Comment by gemmen29** [comment]
You did a great job in implementing the Figma design but I have some suggestions to improve 😃 :

1. Background in contact us and header section in mobile version after the width of 640px need to look like the Figma design.
2. The Portfolio link needs to scroll to the projects section, not the header section.
3. The subheader in the project doesn't look exactly like the Figma design.

That's it Keeps it rock 🚀

**Comment by ShadyShawkat** [comment]
Hey @Omar-Muhamad, 👋🏻 
Very nice work. I like how you documented your code with comments for each section. Your code is looking really clean and thought out. 👏🏻 

I don't think I have anything for you to change. 👍🏻

**Comment by Omar-Muhamad** [comment]
> You did a great job in implementing the Figma design but I have some suggestions to improve 😃 :
> 
> 1. Background in contact us and header section in mobile version after the width of 640px need to look like the Figma design.
> 2. The Portfolio link needs to scroll to the projects section, not the header section.
> 3. The subheader in the project doesn't look exactly like the Figma design.
> 
> That's it Keeps it rock 🚀

Thanks, @gemmen29 
I will take a look at your point and try to improve it.

**Comment by akucintavalent** [comment]
Hey @Omar-Muhamad,
Great job so far, the code is clean and the design of your site looks almost just like the Figma template. There's nothing to change as for now.

**Comment by Omar-Muhamad** [comment]
> Hey @Omar-Muhamad, 👋🏻 Very nice work. I like how you documented your code with comments for each section. Your code is looking really clean and thought out. 👏🏻
> 
> I don't think I have anything for you to change. 👍🏻

Thanks, @ShadyShawkat for your Encouraging words

**Comment by Omar-Muhamad** [comment]
> Hey @Omar-Muhamad, Great job so far, the code is clean and the design of your site looks almost just like the Figma template. There's nothing to change as for now.

Thanks, bohdan for that encouraging words.
